services:
  - name: backend-nodejs
    type: web
    env: node
    region: frankfurt
    branch: main 
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgres://user:password@hostname:5432/dbname # Exemple de variable d'environnement pour PostgreSQL
    plan: free 
    autoDeploy: true 
